#!/usr/bin/env bash
# Copyright (c) 2026 OpenHW Foundation
# SPDX-License-Identifier: Apache-2.0

export UVM_HOME="/opt/accellera/1800.2-2017-1.0/src"
export nproc=2

rm -rf ./obj_dir

verilator -Wno-fatal --binary -j $(nproc) --top-module tbench_top \
    +incdir+$UVM_HOME +define+UVM_NO_DPI +incdir+$(pwd) \
    $UVM_HOME/uvm_pkg.sv $(pwd)/sig_pkg.sv $(pwd)/tb.sv

./obj_dir/Vtbench_top +UVM_TESTNAME=sig_model_test

echo "Ran with:"
echo -n "  "
verilator -version
echo "  UVM_HOME=$UVM_HOME"
